### ISSUE TITLE
Prefix logs with deployment ID and/or now URL

### ISSUE THREAD

**Issue by frolic** [berzniz/now-logs#3]
Thoughts on prefixing log messages with the deployment ID or, better yet, the now URL? These are environment variables that you could pass along as part of the socket.io message and would help to see which log message belongs to which deployments when quickly iterating on a project.

**Comment by berzniz** [comment]
I'm open to pull requests. It should be configurable from the `options` object in some way (https://github.com/berzniz/now-logs/blob/master/lib/nowConsole.js#L10).

**Comment by berzniz** [comment]
Closing due to lack of interest. Will re-open on request
