### ISSUE TITLE
Process keeps running even after ctrl+c

### ISSUE THREAD

**Issue by roborourke** [berzniz/now-logs#4]
I'm not 100% sure how I did it unfortunately but the first time I ran the logs tool I didn't put my secret string in quotes. It contained a bunch of symbols like carets, dollar signs etc eg:

`now-logs 234567^&*$^&$`

I'm running under `zsh`.

Now occasionally when I go back to terminal I can see the `Connected, showing logs for "xyz"` over and over again. I'm not totally sure yet how to kill it.

If you have some ideas what to try it would be much appreciated.

**Comment by roborourke** [comment]
Sorry - quick update, I just force quit every `node` process I had running and it killed 2 hidden logs connections. Maybe there are some extra things that can be done in the code to clean up or kill these processes?

**Comment by berzniz** [comment]
The `&` runs the process in the background. So the best answer is to use quotes
