### ISSUE TITLE
Can't get deployed site logs to show in terminal

### ISSUE THREAD

**Issue by perryraskin** [berzniz/now-logs#5]
Maybe I'm just doing something wrong here? But I'm able to see logs from my site while in localhost, but on the deployed site, logs do not show.

I installed the CLI and the npm package into my app, and added the following line into `next.config.js`:

`require('now-logs')(process.env.LOGS_SECRET);`

And I set up the environment variable correctly and the Now secret, as I've done with all the others.

Appreciate any help here :)

**Comment by berzniz** [comment]
You're not doing something wrong.

This package was intended to the first version of the `now` service. Since then they've added their own logging solutions, so this package is not maintained and I'm not sure it works with all of their infrastructure changes over the years.
